# -*- coding: utf-8 -*-

class Params():
    """Default parameters for UI."""

    CENTROID_MIN_VALUE = 2
    CENTROID_MAX_VALUE = 10
    CENTROID_DEFAULT_VALUE = 2
    CENTROID_FIXED_DEFAULT_VALUE = True

    POPULATION_MIN_VALUE = 5
    POPULATION_MAX_VALUE = 50
    POPULATION_DEFAULT_VALUE = 10

    ITERATION_MIN_VALUE = 10
    ITERATION_MAX_VALUE = 40
    ITERATION_DEFAULT_VALUE = 20

    DATASET_PARSE_FEATURES_DEFAULT_VALUE = False

    CLUSTERING_ALGORITHMS = [u"Elegir", u"K-means", u"Algoritmo Genético"]
    CLUSTERING_PROCESSORS = ['Dummy', 'KMeans', 'Genetic']

    CLUSTERING_ALGORITHM_DEFAULT = 0